### ISSUE TITLE
nan in rgrd using ngwf.set_reach_slope(method='grid_top')

### ISSUE THREAD

**Issue by wkitlasten** [mwtoews/surface-water-network#14]
Probably just need to add a check to set nans to some value, depending on where the nans are being generated.

**Comment by mwtoews** [comment]
Hopefully resolved with c43ae0a05d05e3c2b86ea1f56dddcf2b8f1cd0ea

This will just set them to `min_slope`, which has a default 1./1000 (or 0.001). The NaNs probably get in from [numpy.gradient](https://numpy.org/doc/stable/reference/generated/numpy.gradient.html) along edges that have NaN values in `dis.top`. They might be avoided by defining a full 2D array of DEM values, without any NaN values.

**Comment by wkitlasten** [comment]
Seems to work now. No more nans! Thanks.
