### ISSUE TITLE
flopy SFR package interaction

### ISSUE THREAD

**Issue by briochh** [mwtoews/surface-water-network#2]
There is some behaviour to address related to modifying the flopy segment and reach data frames after undertaking the processing:
    
When initiallising the flopy SFR object any missing column entries are added with default values - totally cool.

However, when updating (e.g. `m.sfr.segment_data = dict`) missing data columns are never constructed - this then falls apart when writing the sfr (see for e.g. around line 1637 of mfsfr2.py). for flexibility at that writing step flopy expects a number of data columns to exist (even if they are infact never used).

Worth noting that `m.sfr.segment_data = dict` approaches will (I think) happily deal with additional data columns in the passed dict (or record arrays) - but the initial constructor will not.

**Comment by mwtoews** [comment]
This is probably fixed by #12 which also re-wrote the MODFLOW support, which now has a `flopy_segment_data()` function to generate this data for flopy.
