### ISSUE TITLE
swn can only be assigned once?

### ISSUE THREAD

**Issue by wkitlasten** [mwtoews/surface-water-network#31]
I just pulled from main to make sure I was updated and started getting the following error after trying to load the pickle. Thoughts?

```
ngwf = swn.SwnMf6.from_pickle(ppth,gwf)
```

```
File "d:\modelling\surface-water-network\swn\modflow\_base.py", line 126, in from_pickle
    obj.swn = swn

  File "d:\modelling\surface-water-network\swn\modflow\_base.py", line 152, in swn
    raise AttributeError("swn property can only be set once")

AttributeError: swn property can only be set once
```

**Comment by mwtoews** [comment]
Aha, I just got caught by this one too. It's a misleading message, which needs to be fixed to close this issue. The reason why is that I've changed the arguments. Try this:

    ngwf = swn.SwnMf6.from_pickle(ppth, model=gwf)

or if you have a `SurfaceWaterNetwork` object `n`:

    ngwf = swn.SwnMf6.from_pickle(ppth, n, gwf)

**Comment by wkitlasten** [comment]
Still running into issues:

```
  ngwf = swn.SwnMf6.from_pickle(ppth, swn=n, model=gwf)

  File "d:\modelling\surface-water-network\swn\modflow\_base.py", line 128, in from_pickle
    obj.model = model

  File "d:\modelling\surface-water-network\swn\modflow\_base.py", line 194, in model
    str(type(model)))

ValueError: model must be a flopy.mf6.MFModel object; found <class 'flopy.mf6.mfmodel.MFModel'>


type(gwf)
Out[17]: flopy.mf6.mfmodel.MFModel
```

I think the message should be "model must be a flopy.mf6.**mfmodel**.MFModel object" based on the conditional:

```if not (isinstance(model, flopy.mf6.mfmodel.MFModel)):```

But still not sure why my gwf is not passing:

```
gwf
Out[19]: 
name = wairau_240_15
model_type = gwf
version = mf6
model_relative_path = 

<plus all the packages listed as expected>
```
