### ISSUE TITLE
Another shapely deprecation warning trigger

### ISSUE THREAD

**Issue by briochh** [mwtoews/surface-water-network#39]
@mwtoews another spot where we a triggering a shapely deprecation warning.

Are we happy to just be swallowing these for now?

https://github.com/mwtoews/surface-water-network/blob/63cc21ca72d95e150dbeb7789a4364b1339ae9a8/swn/modflow/_base.py#L559

**Comment by mwtoews** [comment]
I haven't seen this, is it still happening? If so, just list the package versions and I'll fix. But I'm guessing this might have been resolved with various package updates.
